server:
  port: 8770
spring:
  application:
    name: cloud-security
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
security:
  oauth2:
    resource:
      filter-order: 3 #不加的話, 就算header裡有正確的Authorization, 還是會一直導到登入頁